#!/usr/bin/env python3

import boto3
import requests

url = input("input the url of the file you wish to save and upload: ")
local_gif = "file.gif"

response = requests.get(url)

with open(local_gif, 'wb') as f:
  f.write(response.content)
print(f"downloaded file and saved in local path as {local_gif}")

s3 = boto3.client('s3', region_name='us-east-1')

# vars needed
bucket_name = input("please enter s3 bucket name: ")
object_name = input("please enter the name to save file as in s3: ")
expires_in = 604800

s3.upload_file(local_gif, bucket_name, object_name, ExtraArgs={'ACL': 'public-read'})

response = s3.generate_presigned_url(
    'get_object',
    Params={'Bucket': bucket_name, 'Key': object_name},
    ExpiresIn=expires_in,
    )

